In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("./Customer Segmentation.csv")
df

,Unnamed: 0,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,0,460394,Female,No,32,Yes,Healthcare,9.0,Low,3.0,Cat_6,D
1,1,461798,Female,No,56,Yes,Artist,0.0,Low,1.0,Cat_6,A
2,2,464976,Male,Yes,75,No,Lawyer,1.0,Low,1.0,Cat_4,D
3,3,462104,Male,Yes,39,No,Entertainment,9.0,Low,2.0,Cat_3,D
4,4,464829,Male,No,22,No,Healthcare,9.0,Low,5.0,Cat_4,D
...,...,...,...,...,...,...,...,...,...,...,...,...
10690,10690,462861,Female,No,30,Yes,Healthcare,8.0,Low,1.0,Cat_6,D
10691,10691,464409,Female,Yes,81,Yes,Lawyer,0.0,Average,2.0,Cat_6,A
10692,10692,465861,Female,No,40,Yes,Entertainment,14.0,Low,1.0,Cat_6,A
10693,10693,465056,Male,Yes,87,Yes,Lawyer,1.0,High,2.0,Cat_6,A
10694,10694,461637,Male,Yes,51,Yes,Artist,1.0,Low,2.0,Cat_7,B

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10695 entries, 0 to 10694
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       10695 non-null  int64
 1   ID               10695 non-null  int64
 2   Gender           10695 non-null  object
 3   Ever_Married     10505 non-null  object
 4   Age              10695 non-null  int64
 5   Graduated        10593 non-null  object
 6   Profession       10533 non-null  object
 7   Work_Experience  9597 non-null   float64
 8   Spending_Score   10695 non-null  object
 9   Family_Size      10247 non-null  float64
 10  Var_1            10587 non-null  object
 11  Segmentation     10695 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 1002.8+ KB

In [4]:
df.isnull().sum()

Unnamed: 0            0
ID                    0
Gender                0
Ever_Married        190
Age                   0
Graduated           102
Profession          162
Work_Experience    1098
Spending_Score        0
Family_Size         448
Var_1               108
Segmentation          0
dtype: int64

In [5]:
df.describe()

,Unnamed: 0,ID,Age,Work_Experience,Family_Size
count,10695.000000,10695.000000,10695.000000,9597.000000,10247.000000
mean,5347.000000,463468.088640,43.511828,2.619777,2.844052
std,3087.524899,2600.966411,16.774158,3.390790,1.536427
min,0.000000,458982.000000,18.000000,0.000000,1.000000
25%,2673.500000,461220.500000,30.000000,0.000000,2.000000
50%,5347.000000,463451.000000,41.000000,1.000000,3.000000
75%,8020.500000,465733.500000,53.000000,4.000000,4.000000
max,10694.000000,467974.000000,89.000000,14.000000,9.000000

In [6]:
import numpy as np

In [7]:
df = df.replace('NaN', np.nan)

In [8]:
df['Var_1'] = df['Var_1'].fillna(df['Var_1'].mode()[0])
df['Graduated'] = df['Graduated'].fillna(df['Graduated'].mode()[0])
df['Profession'] = df['Profession'].fillna(df['Profession'].mode()[0])
df['Family_Size'] = df['Family_Size'].fillna(df['Family_Size'].median())
df['Work_Experience'] = df['Work_Experience'].fillna(df['Work_Experience'].median())
df['Ever_Married'] = df['Ever_Married'].fillna(df['Ever_Married'].mode()[0])

In [9]:
df.isnull().sum()

Unnamed: 0         0
ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
Segmentation       0
dtype: int64

In [10]:
# getting the distinct values of the variable.
df["Segmentation"].unique()

array(['D', 'A', 'C', 'B'], dtype=object)

In [11]:
df["Var_1"].unique()

array(['Cat_6', 'Cat_4', 'Cat_3', 'Cat_2', 'Cat_7', 'Cat_1', 'Cat_5'],
      dtype=object)

## Label Encoding

In [12]:
df["Spending_Score"] = df["Spending_Score"].map({"Low":0, "Average":1, "High":2})

In [13]:
df["Gender"] = df["Gender"].map({"Female":0, "Male":1})

In [14]:
df["Ever_Married"] = df["Ever_Married"].map({"No":0, "Yes":1})

In [15]:
df["Segmentation"] = df["Segmentation"].map({"A":0, "B":1, "C":2, "D":3})

In [16]:
df["Var_1"] = df["Var_1"].map({"Cat_1":0, "Cat_2":1, "Cat_3":2, "Cat_4":3,"Cat_5":4, "Cat_6":5, "Cat_7":6})

In [17]:
x = df[["Age", "Gender", "Ever_Married", "Segmentation", "Var_1"]]
y = df["Spending_Score"]

## Optimal Feature Selection

In [18]:
from sklearn.feature_selection import SelectKBest,f_classif

In [19]:
## Instanting selectKBest
select = SelectKBest(f_classif, k = 4)
x_select = select.fit_transform(x,y)

# Getting the column names
column_name = x.columns[select.get_support()]
column_name

Index(['Age', 'Ever_Married', 'Segmentation', 'Var_1'], dtype='object')

In [20]:
x_new = df[['Age', 'Ever_Married', 'Segmentation', 'Var_1']]

In [21]:
x_transf = np.sqrt(x_new)
x_transf

            Age  Ever_Married  Segmentation     Var_1
0      5.656854           0.0      1.732051  2.236068
1      7.483315           0.0      0.000000  2.236068
2      8.660254           1.0      1.732051  1.732051
3      6.244998           1.0      1.732051  1.414214
4      4.690416           0.0      1.732051  1.732051
...         ...           ...           ...       ...
10690  5.477226           0.0      1.732051  2.236068
10691  9.000000           1.0      0.000000  2.236068
10692  6.324555           0.0      0.000000  2.236068
10693  9.327379           1.0      0.000000  2.236068
10694  7.141428           1.0      1.000000  2.449490

[10695 rows x 4 columns]

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
xtrain, xtest, ytrain, ytest = train_test_split(x_new, y, test_size = 0.3, random_state = 42)
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((7486, 4), (3209, 4), (7486,), (3209,))

## HyperParameter Tuning

In [24]:
param = {
    'criterion':["gini", "entropy"],
    'max_depth':[3, 4, 5, 6, 7],
    'max_features':[2, 3, 4, 5, 6],
    'min_samples_split':[2,3,4]
}

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
from sklearn.model_selection import GridSearchCV

In [27]:
dt = DecisionTreeClassifier(random_state = 42)

In [28]:
gs = GridSearchCV(dt, param_grid = param, cv = 10)
model = gs.fit(xtrain,ytrain)
model

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 5, 6, 7],
                         'max_features': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4]})

In [29]:
y_pred = model.predict(xtest)
y_pred

array([1, 0, 2, ..., 0, 2, 0], shape=(3209,))

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [31]:
acc = accuracy_score(ytest,y_pred)
acc

0.7154876908694298

In [32]:
cm = confusion_matrix(ytest,y_pred)
cm

array([[1595,  279,   85],
       [ 193,  563,   33],
       [ 131,  192,  138]])